name: cfpad
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - numpy
    - pandas
    - pytorch
    - torchvision
    - torchaudio
    - scikit-learn
    - tqdm
    - opencv
    - albumentations